<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: uahoo
 * Date: Fri, 07 Feb 2014 11:15:04 +0800
 */

$conf['title'] = '基于Git的版本控制与发布部署';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['subscribers'] = 1;

// end auto-generated content
