<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: uahoo
 * Date: Thu, 05 Dec 2013 15:26:58 +0800
 */

$conf['title'] = '基于Git的代码管理和发布部署';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
