<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: uahoo
 * Date: Tue, 28 Jan 2014 11:29:34 +0800
 */

$conf['title'] = '基于Git的代码管理和发布部署';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['subscribers'] = 1;

// end auto-generated content
